#!/usr/bin/env php
<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * svn pre-commit hook which will run given tests using Muhafiz
 */
$configFile = $argv[1] . '/conf/muhafiz.conf';

if (!file_exists($configFile) || ($GLOBALS['svnconfig'] = parse_ini_file($configFile, true)) === false) {
    error_log("Bootstrap path not set properly. Cannot continue! Check your ${configFile}\n");
    exit(1);
}

$bootstrapFile = $GLOBALS['svnconfig']['muhafiz']['bootstrap-file'];

$GLOBALS['dir'] = realpath(__DIR__ ."/../../");
$GLOBALS['vcs'] = 'subversion';
$GLOBALS['hookType'] = "pre-commit";
include_once($bootstrapFile);

